### ISSUE TITLE
やるといいことと難易度

### ISSUE THREAD

**Issue by enp1s0** [rioyokotalab/mnist_train#1]
[変数名対応図(PDF)](https://github.com/rioyokotalab/mnist_train/files/3742495/mnist_train.pdf)

変数の役割が知りたければPDF内で検索をかければ見つかると思います．

**Level-1.0**
- `elementwise_product`, `ReLU`, `dReLU` のカーネル関数を実装  
  ほとんどadd_vecのサンプルコードのカーネル関数と同じ

**Level-1.5**
- `add_bias` のカーネル関数を実装  
  ![IMG_0070](https://user-images.githubusercontent.com/12711693/65599441-cf93a300-dfd8-11e9-95c7-8dfce9f55eb2.png)

**Level-2.0**
- `softmax` のカーネル関数を実装
  - CUDAの組み込み関数`expf`を使うといいかも
![IMG_0073](https://user-images.githubusercontent.com/12711693/65599634-429d1980-dfd9-11e9-996c-308c5aa08fe8.PNG)

**Level-3.0**
- `matmul`, `matmul_tn`, `gemm_nt`のカーネル関数を実装
  - `matmul` : C <- A x B
  - `matmul_tn` : C <- A^t x B
  - `gemm_nt` : C <- alpha x A x B^t + beta x C

  行列サイズ（M, N, K）は一般にこんな感じ
![IMG_0074](https://user-images.githubusercontent.com/12711693/65600132-7fb5db80-dfda-11e9-9ba5-1873bf6dff51.PNG)

**Level-4.0**
- `matmul`, `matmul_tn`, `gemm_nt`の高速化
  - Sharedメモリやレジスタでブロッキングを行って行列積を高速化
  - [この論文](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6114452)が理論的に最適なブロッキングサイズを決定するのに役立つかも

**Level-5.0** (やらなくていいよ)
- 畳み込み層の実装
  - CIFAR-10の読み込み関数は[こちら](https://github.com/enp1s0/cifar-10-loader)をどうぞ
  - 畳み込みを行うのであればim2colという入力画像をカーネルに合わせて行列の形に変更するアルゴリズムを用いると高速化できるかも
  - 愚直にカーネルを走査させながら畳み込んでももちろんOK

Happy parallel life.

**Comment by rioyokota** [comment]
レポートの内容 (10/21(月) 23:59締切)

- <<<*,ブロックサイズ>>>を変えて計算時間がどう変わるかを3.4通りぐらい調べる
- minibatch_sizeを変えて学習の精度・速度がどう変わるかを調べる
- hidden_sizeを変えて学習の精度・速度がどう変わるかを調べる
- 自分で好きなことをやる

[追記(大友)] 提出メールでお願いします

**Comment by enp1s0** [comment]
カーネル関数呼び出し後に
```cuda
// hoge_kernel <<< 10, 256 >>> (...);
cudaDeviceSynchronize();
```
を呼ばないと計算結果がおかしくなる問題がありました．
念の為カーネル関数を呼んだあとは`cudaDeviceSynchronize`を呼んでください．

**Comment by rioyokota** [comment]
CUDA API
https://docs.nvidia.com/cuda/cuda-runtime-api/index.html
