### ISSUE TITLE
loginできません

### ISSUE THREAD

**Issue by rioyokota** [rioyokotalab/mnist_train#2]
ssh guest@login.rio.gsic.titech.ac.jp
と入力してもpermission denied でエラーが出ました

**Comment by enp1s0** [comment]
すみません。
修正しました。
改善されていないようでしたらjumpcloudでguestのグループをstudentsに変更していただけたらと思います。

**Comment by rioyokota** [comment]
あ，すみません．これはテストです．

**Comment by rioyokota** [comment]
無視してください
